---
# handlers file for postgresql
- name: Restart postgresql
  ansible.builtin.service:
    name: "{{ postgresql_service.name }}"
    state: restarted

- name: Restore selinux contexts
  ansible.builtin.command: restorecon -R -v {{ postgresql.base_directory }}
