---
- name: Generate client certificate
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: Install openssl
      ansible.builtin.yum:
        name: openssl
        state: present
    - name: Create self-signed SSL certificate for the client
      ansible.builtin.include_role:
        name: "mirsg.ssl_certificates"

- name: Converge
  hosts: db
  become: true
  gather_facts: true
  tasks:
    - name: Create and setup a postgresql database
      ansible.builtin.include_role:
        name: "mirsg.postgresql"
