---
- name: Prepare
  hosts: web
  become: true
  gather_facts: true
  tasks:
    - name: Install openssl
      ansible.builtin.yum:
        name: openssl
        state: present
    - name: Create self-signed SSL certificate for the client
      ansible.builtin.include_role:
        name: "mirsg.ssl_certificates"
      vars:
        ssl_certificate: "{{ postgresql_client_ssl_certificate }}"
